characters:
  - index:
    - レオン
    - リリア
    - マル爺
    - フェリエラ
    - クレイド
    - ローゼリア
    - テレスティ


  ##         #######     ######     ###    ## 
  ##         ##         ##    ##    ####   ## 
  ##         #####      ##    ##    ## ##  ## 
  ##         ##         ##    ##    ##  ## ## 
  #######    #######     ######     ##   #### 


  - name: レオン
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:



  ##         ##    ##         ##    ##     #####  
  ##         ##    ##          ##  ##     ##   ## 
  ##         ##    ##           ####      ####### 
  ##         ##    ##            ##       ##   ## 
  #######    ##    #######       ##       ##   ## 


  - name: リリア
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |
          幼少の頃、誤って姉に大怪我をさせてしまったことがトラウマになっていて強くなるのが怖い
          これまでその恐怖と戦いながら強くなってきたがその先へ進むことができないでいる
      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:



  ###    ###     #####     ######     ########    ##    ###    ##    ##    ##    ####### 
  ####  ####    ##   ##    ##   ##       ##       ##    ####   ##    ##    ##    ##      
  ## #### ##    #######    ######        ##       ##    ## ##  ##    ##    ##    ####### 
  ##  ##  ##    ##   ##    ##   ##       ##       ##    ##  ## ##    ##    ##         ## 
  ##      ##    ##   ##    ##   ##       ##       ##    ##   ####     ######     ####### 


  - name: マル爺
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:



  #######    #######    ##         ##    #######    ######      #####  
  ##         ##         ##         ##    ##         ##   ##    ##   ## 
  #####      #####      ##         ##    #####      ######     ####### 
  ##         ##         ##         ##    ##         ##   ##    ##   ## 
  ##         #######    #######    ##    #######    ##   ##    ##   ## 


  - name: フェリエラ
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:



   ######    ##         #######    ##    ##    ######  
  ##         ##         ##          ##  ##     ##   ## 
  ##         ##         #####        ####      ##   ## 
  ##         ##         ##            ##       ##   ## 
   ######    #######    #######       ##       ######  


  - name: クレイド
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:



  ######      ######     #######    #######    ##         ##    ##     #####  
  ##   ##    ##    ##    ##         ##         ##          ##  ##     ##   ## 
  ######     ##    ##    #######    #####      ##           ####      ####### 
  ##   ##    ##    ##         ##    ##         ##            ##       ##   ## 
  ##   ##     ######     #######    #######    #######       ##       ##   ## 


  - name: ローゼリア
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:



  ########    ##   ##    #######    ######     #######    #######    ########    ##    ## 
     ##       ##   ##    ##         ##   ##    ##         ##            ##        ##  ##  
     ##       #######    #####      ######     #####      #######       ##         ####   
     ##       ##   ##    ##         ##   ##    ##              ##       ##          ##    
     ##       ##   ##    #######    ##   ##    #######    #######       ##          ##    


  - name: テレスティ
    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

