characters:


 ######     ##     ##       ###       ########        ###        ######     ########    ########    ########      ######  
##    ##    ##     ##      ## ##      ##     ##      ## ##      ##    ##       ##       ##          ##     ##    ##    ## 
##          ##     ##     ##   ##     ##     ##     ##   ##     ##             ##       ##          ##     ##    ##       
##          #########    ##     ##    ########     ##     ##    ##             ##       ######      ########      ######  
##          ##     ##    #########    ##   ##      #########    ##             ##       ##          ##   ##            ## 
##    ##    ##     ##    ##     ##    ##    ##     ##     ##    ##    ##       ##       ##          ##    ##     ##    ## 
 ######     ##     ##    ##     ##    ##     ##    ##     ##     ######        ##       ########    ##     ##     ######  


  - index:
    - レオン
    - リリア
    - マル爺
    - フェリエラ
    - テレスティ
    - クレイド
    - ローゼリア
    - ヴェトラヤル

  - name: レオン


      ##         #######     ######     ###    ## 
      ##         ##         ##    ##    ####   ## 
      ##         #####      ##    ##    ## ##  ## 
      ##         ##         ##    ##    ##  ## ## 
      #######    #######     ######     ##   #### 


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: リリア


##         ##    ##         ##    ##     #####  
##         ##    ##          ##  ##     ##   ## 
##         ##    ##           ####      ####### 
##         ##    ##            ##       ##   ## 
#######    ##    #######       ##       ##   ## 


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |
          幼少の頃、誤って姉に大怪我をさせてしまったことがトラウマになっていて強くなるのが怖い
          これまでその恐怖と戦いながら強くなってきたがその先へ進むことができないでいる
      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: マル爺


###    ###     #####     ######     ########    ##    ###    ##    ##    ##    ####### 
####  ####    ##   ##    ##   ##       ##       ##    ####   ##    ##    ##    ##      
## #### ##    #######    ######        ##       ##    ## ##  ##    ##    ##    ####### 
##  ##  ##    ##   ##    ##   ##       ##       ##    ##  ## ##    ##    ##         ## 
##      ##    ##   ##    ##   ##       ##       ##    ##   ####     ######     ####### 


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: フェリエラ


#######    #######    ##         ##    #######    ######      #####  
##         ##         ##         ##    ##         ##   ##    ##   ## 
#####      #####      ##         ##    #####      ######     ####### 
##         ##         ##         ##    ##         ##   ##    ##   ## 
##         #######    #######    ##    #######    ##   ##    ##   ## 


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: テレスティ


########    ##   ##    #######    ######     #######    #######    ########    ##    ## 
   ##       ##   ##    ##         ##   ##    ##         ##            ##        ##  ##  
   ##       #######    #####      ######     #####      #######       ##         ####   
   ##       ##   ##    ##         ##   ##    ##              ##       ##          ##    
   ##       ##   ##    #######    ##   ##    #######    #######       ##          ##    


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: クレイド


   ######    ##         #######    ##    ##    ######  
  ##         ##         ##          ##  ##     ##   ## 
  ##         ##         #####        ####      ##   ## 
  ##         ##         ##            ##       ##   ## 
   ######    #######    #######       ##       ######  


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: ローゼリア


  ######      ######     #######    #######    ##         ##    ##     #####  
  ##   ##    ##    ##    ##         ##         ##          ##  ##     ##   ## 
  ######     ##    ##    #######    #####      ##           ####      ####### 
  ##   ##    ##    ##         ##    ##         ##            ##       ##   ## 
  ##   ##     ######     #######    #######    #######       ##       ##   ## 


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:

  - name: ヴェトラヤル


##    ##    #######    ########    ######      #####     ##    ##     #####     ##      
##    ##    ##            ##       ##   ##    ##   ##     ##  ##     ##   ##    ##      
##    ##    #####         ##       ######     #######      ####      #######    ##      
 ##  ##     ##            ##       ##   ##    ##   ##       ##       ##   ##    ##      
  ####      #######       ##       ##   ##    ##   ##       ##       ##   ##    ####### 


    characteristics:
      name:
        formal name: 
        nick name: 
        popular name: 
        origin of first name: 
        origin of family name: 
        origin of nick name: 
        origin of popupar name: 
      inherent:
        race: 
        gender: 
        age: 
      physical:
        outline: |

        height: 
        weight:
        hair color:  
        hair style: 
        eyes: 
        3 size:
          bust: 
          west: 
          hip: 
      personality:
        outline: |

        features:
          - 
          - 
          - 
          - 
        trauma: |

      status:
        job: 
      history:
        parents:
          father: 
          mother: 
          grand father:
            - 
            - 
          grand mother:
            - 
            - 
        birth: 
        growing environment: |

        contacts:
          - name: 
            relationship: 
            episodes:
              - 
      etc:
        - 

things:


########    ##     ##    ####    ##    ##     ######       ######  
   ##       ##     ##     ##     ###   ##    ##    ##     ##    ## 
   ##       ##     ##     ##     ####  ##    ##           ##       
   ##       #########     ##     ## ## ##    ##   ####     ######  
   ##       ##     ##     ##     ##  ####    ##    ##           ## 
   ##       ##     ##     ##     ##   ###    ##    ##     ##    ## 
   ##       ##     ##    ####    ##    ##     ######       ######  


  - index:
    - レウネ
    - カヴァネラ暗号
    - アグニソルスース

  - name: レウネの黒柱
    description:
      - 両手で持つほどの黒い柱
      - カヴァネラ暗号による暗号文が表面を覆い尽くしている

  - name: レウネ
    description:
      - 古代アールクヴィストの三賢者の一人。カヴァネラ暗号の開発者

  - name: カヴァネラ暗号
    description:
      - レウネによって開発された暗号方式。ウィジャハの魔法定理を使って作られてる。カヴァネラの街でレウネが作った。アグニソルスース神殿に奉献された

  - name: ウィジャハの魔法定理
    description:
      - 

  - name: ウィジャハ
    description:
      - 

  - name: アグニソルスース
    description:
      - 鍵と秘匿の古代神

  - name: 
    description:
      - 

  - name: 
    description:
      - 


etc:
  - ヴェトラヤルが封印されているため、逆にアルメクトからも干渉できない
  - アルメクトがヴェトラヤルのレオンたちへの追跡を妨害しているため、ヴェトラヤルはレオンたちが神殿に現れたときにしか補足できない
  - マル爺はかつて◯◯神と契約し、その権能で呪毒解除の魔法を使えるようになった。だが神との契約において命の供与を約束している。にもかかわらずマル爺は呪毒解除の魔法を行使する際に生き延びたいとの心が芽生えた。その契約違反によって魔法は成らず、かつ喜びの感情を失った
  - ヴェトラヤルはアルメクトの姉
